from collections import Counter, defaultdict
import re

text = """IM A SHELL OF MYSELF - I TRY TO WRITE SOMETHING SO PROFOUND THAT IT WILL BEAT THE IRONY EPIDEMIC, THE ARTIST'S BREIFS YOU IGNORE AND THE CAPTION THAT IS AI GENERATED. 
IM IN THE LOOP OF WANTING TO REACH GREATNESS WITH NO MEANS. NO WAY TO GET THERE, BUT IM TOO LAZY TO MAKE MY PATH. 
DO I FALL VICTIM TO THE LACK OF "GRINDSET", BUT NO. I WIAS TOLD IT WAS MADE TO MAKE MILLIONS OFF PEOPLE'S WILLINGBNESS TO MAKE IT BIG. 
BUT I WANT TO WRITE SOMETHING SO PROFOUND. 
DO I SAY SOMETHING CONTROVERSIAL THAT I DONT KNOW THE MEANING, BUT I MAKE EVERYONE AROUND ME TRY TO MAKE MEANING FROM IT. 
DO YOU THINK EVERYTHING I DO MAKES FOR A STORY FOR MY FANS WILL SHARE. WILL I EVER HAVE FANS? WHY WOULD THEY LIKE ME? 
I WONDER IF I WILL EVER MAKE A PIECE OF MEDIA SO PROFOUND, IF I EVER GO INTO HIDING, THEY WILL STILL LOVE ME? 
I WONDER WHAT THAT ADMIRATION WILL FEEL LIKE? 
I WONDER IF EVER TO STICK TO A PROJECT LONG ENOUGH, TO RELEASE TO WARRANT SUCH A THING. 
I FEEL MYSELF. RIGHT NOW. BE UNSURE WITH WHAT IM SAYING. AS I THINK MORE AND MORE. 
I GROW LESS IN MY WORDS, MY WRITING, MY CONVICTION AND MY GOAL. I CANT EVEN HAVE A CLEAR IMAGE OF STABLE MUNDANE. 
SO I STRIVE FOR INCREDIBLE FAME, TO OFFSET THE FACT I CANT FIGURE OUT THE NORMACALLY OF LIVING. 
BEING ABLE TO DO SUCH A THING MY GOAL, I GUESS. I DECIDED RIGHT NOW. YEAH. LIFE DOES NOT HAVE TO BE HARD. 
MIDST PEOPLE NEVER CREATE ANYTHING MEANINGFUL. AND I THINK THATS FINE. I KNOW MY STATEMENT IS NOT PROFOUND. 
I GUESS I NEEDED THIS TO GET THERE MYSELF. 
I THINK OF MYSELF NOW. I WANT TO BE CONSCIENTIOUSNESS OF MY LIFE CAN BE WITH THE CHOICES I MAKE. 
TO MAKE SURE I HAVE FULFILLMENT IN THE COMFORT WHERE I AM. AT ANY TIME. ANY WHERE. 
WITH THE PEOPLE AROUND ME. TO SHARE WITH OUT BEING ATTACKED. AND BE LIFTED TO REACH MY POTENITAL.  """

cleaned = re.sub(r'[^A-Z]', '', text.upper())

def best_ngrams(text, max_n=7, min_freq=2):
    ngram_freq = defaultdict(Counter)
    for n in range(1, max_n+1):
        for i in range(len(text) - n + 1):
            gram = text[i:i+n]
            ngram_freq[n][gram] += 1

    best = {}
    for n in sorted(ngram_freq.keys()):
        filtered = [(g, c) for g, c in ngram_freq[n].most_common() if c >= min_freq]
        if filtered:
            best[n] = filtered
    return best

top_grams = best_ngrams(cleaned, max_n=7, min_freq=5)

for n, grams in top_grams.items():
    print(f"\nTop {n}-grams (freq ≥ 2):")
    for gram, count in grams:
        print(f"  {gram} : {count}")